<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

// 分期付款
class Installment extends Model
{
    protected $fillable = [
        'no',
        'total_amount',
        'count',
        'free_rate',
        'fine_rate',
        'status'
    ];

    const STATUS_PENDING = 'pending';
    const STATUS_REPAYING = 'repaying';
    const STATUS_FINISH = 'finish';

    public static $statusMap = [
        self::STATUS_REPAYING => '还款中',
        self::STATUS_PENDING => '待还款',
        self::STATUS_FINISH => '已完成'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            // 如果模型的no为空
            if (!$model->no) {
                // 调用 findAvailableNo 生成流水单号
                $model->no = $this->findAvailableNo();
                // 如果生成失败, 则终止订单创建
                if (!$model->no) {
                    return false;
                }
            }
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function items()
    {
        return $this->hasMany(InstallmentItem::class);
    }

    public function findAvailableNo()
    {
        // 分期流水号前缀
        $prefix = date('YmdHis');
        for ($i = 0; $i < 10; $i ++) {
            // 随机生成 6 位数字
            $no = $prefix . str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
            // 判断是否存在
            if (!static::query()->where('no', $no)->exists()) {
                return $no;
            }
        }
        Log::warning('find installment no failed');
    }
}
